server:
  port: 8080
spring:
  application:
    name: XinMiaoStudent
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/Xin_Miao_Student?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: username
      password: password
  mail:
    host: smtp.qq.com
    username: username
    password: password
    default-encoding: UTF-8
  servlet:
    multipart:
      max-file-size: 10MB
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: ASSIGN_ID
xin-miao-student:
  photo:
    path: E:\code_exercise\Java\XinMiaoStudent\src\main\resources\photo\